// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProiectOpt.Models
{
    public class Client
    {
        public int Id { get; set; }
        public string NumeClient { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Parola { get; set; }
    }
}