// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProiectOpt.Models
{
    public class Fabricant
    {
        public int Id { get; set; }
        public string FabricantNume { get; set; }
    }
}