// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProiectOpt.Models
{
    public class Instrument
    {
        public int Id { get; set; }
        public string InstrumentNume { get; set; }
        public int FabricantId { get; set; }
        public int CategorieId { get; set; }
        public string InstrumentDescriere { get; set; }
        public string InstrumentPoza { get; set; }

        public Fabricant Fabricant { get; set; }

        public Categorie Categorie { get; set; }
    }
}