// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProiectOpt.Models
{
    public class ItemComanda
    {
        public int Id { get; set; }
        public int ComandaClientId { get; set; }
        public int ItemId { get; set; }
        public int Pret { get; set; }

        public ComandaClient ComandaClient { get; set; }

        public Item Item { get; set; }
    }
}