// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProiectOpt.Models
{
    public class Item
    {
        public int Id { get; set; }
        public int InstrumentId { get; set; }
        public string ItemDescriere { get; set; }
        public string ItemPoza { get; set; }
        public int Pret { get; set; }

        public Instrument Instrument { get; set; } 
    }
}